CREATE TABLE KDA_T(
NAME VARCHAR2(50) PRIMARY KEY,
AGE NUMBER
);

Drop Table KDA_T;

INSERT INTO KDA_T
VALUES('Dima', 21);
INSERT INTO KDA_T
VALUES('Valeriy', 19);
INSERT INTO KDA_T
VALUES('Vova', 23);

Select * FROM KDA_T;