ALTER SESSION  Set "_oracle_script" = TRUE;
ALTER SESSION SET CONTAINER = PDB_KDA;
ALTER SESSION SET CONTAINER = CDB$ROOT;

--1
CREATE USER KDA IDENTIFIED BY 12345;

GRANT CREATE SESSION TO KDA;
GRANT CREATE TABLE TO KDA;
GRANT CREATE TABLESPACE TO KDA;
GRANT CREATE SEQUENCE TO KDA;
ALTER USER KDA QUOTA 10M ON USERS;
GRANT CREATE CLUSTER TO KDA;
GRANT CREATE SYNONYM TO KDA;
GRANT CREATE PUBLIC SYNONYM TO KDA;
GRANT DROP PUBLIC SYNONYM TO KDA;
GRANT CREATE VIEW TO KDA;
GRANT CREATE MATERIALIZED VIEW TO KDA;
GRANT QUERY REWRITE TO KDA;
GRANT CREATE DATABASE LINK TO KDA;

DROP USER KDA CASCADE;

--2
CREATE GLOBAL TEMPORARY TABLE SOMETABLE 
(
ID_PERSON NUMBER,
NAME_PERSON VARCHAR2(50)
) ON COMMIT PRESERVE ROWS;

INSERT INTO SOMETABLE VALUES (1, 'BOBR');

SELECT * FROM SOMETABLE;

--3
CREATE SEQUENCE S1
INCREMENT BY 10
START WITH 1000
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE
NOORDER

SELECT S1.NEXTVAL FROM DUAL;
SELECT S1.CURRVAL FROM DUAL;

DROP SEQUENCE S1;

--4
CREATE SEQUENCE S2
INCREMENT BY 10
START WITH 10
MAXVALUE 100
NOCYCLE

SELECT S2.NEXTVAL FROM DUAL;

DROP SEQUENCE S2;

--5
CREATE SEQUENCE S3
INCREMENT BY -10
START WITH -10
MINVALUE -100
NOMAXVALUE
NOCYCLE
ORDER

SELECT S3.NEXTVAL FROM DUAL;

DROP SEQUENCE S3;

--6
CREATE SEQUENCE S4
INCREMENT BY 1
START WITH 1
MAXVALUE 10
CYCLE
CACHE 5
NOORDER 

SELECT S4.NEXTVAL FROM DUAL;

DROP SEQUENCE S4;

--7
SELECT * FROM SYS.USER_SEQUENCES;

--8
CREATE TABLE T1(
N1 NUMBER(20),
N2 NUMBER(20),
N3 NUMBER(20),
N4 NUMBER(20)
)
STORAGE(BUFFER_POOL KEEP) TABLESPACE USERS CACHE;

INSERT INTO T1 VALUES (S1.NEXTVAL, S2.NEXTVAL, S3.NEXTVAL, S4.NEXTVAL);

SELECT * FROM T1

DROP TABLE T1;

--9
CREATE CLUSTER ABC(
X NUMBER(10),
V VARCHAR2(12)
)
HASHKEYS 200; --hash-тип

DROP CLUSTER ABC;

--10
CREATE TABLE A(
XA NUMBER(10),
VA VARCHAR2(12),
XV VARCHAR2(22)
);

DROP TABLE A;

-11
CREATE TABLE B(
XB NUMBER(10),
VB VARCHAR2(12),
VX VARCHAR2(22)
);

DROP TABLE B;

--12
CREATE TABLE C(
XC NUMBER(10),
VC VARCHAR2(12),
MU VARCHAR2(22)
);

DROP TABLE C;

--13
SELECT CLUSTER_NAME, OWNER, TABLESPACE_NAME, CLUSTER_TYPE, CACHE FROM DBA_CLUSTERS;

--14
CREATE SYNONYM KDA FOR KDA.C;

SELECT * FROM KDA;

DROP SYNONYM KDA;

--15
CREATE PUBLIC SYNONYM KD FOR KDA.B;
SELECT * FROM KD;

--16
CREATE TABLE A(
ID_PERSON NUMBER(20),
NAME_PERSON NVARCHAR2(50),
CONSTRAINT PK_A PRIMARY KEY(ID_PERSON)
);

CREATE TABLE B(
AGE_PERSON NUMBER(20),
COUNTRY_PERSON NVARCHAR2(50),
ID_PERSON NUMBER(20),
CONSTRAINT FK_B FOREIGN KEY(ID_PERSON)REFERENCES A(ID_PERSON)
);

INSERT INTO A VALUES(1, 'Alexsey');
INSERT INTO A VALUES(2, 'Daniil');
INSERT INTO A VALUES(3, 'Urmat');
INSERT INTO A VALUES(4, 'Vladimir');

SELECT * FROM A;

INSERT INTO B VALUES(18, 'Belarus', 1);
INSERT INTO B VALUES(19, 'Belarus', 2);
INSERT INTO B VALUES(20, 'Belarus', 3);
INSERT INTO B VALUES(19, 'Belarus', 4);

SELECT * FROM B;

CREATE VIEW INFO_PERSONS AS SELECT A.NAME_PERSON, B.AGE_PERSON, B.COUNTRY_PERSON
FROM A INNER JOIN B
ON A.ID_PERSON = B.ID_PERSON;

SELECT * FROM INFO_PERSONS;

--17
CREATE MATERIALIZED VIEW MV_KDA
REFRESH COMPLETE ON DEMAND 
NEXT SYSDATE + NUMTODSINTERVAL (2, 'MINUTE') AS SELECT A.NAME_PERSON, B.AGE_PERSON, B.COUNTRY_PERSON
FROM A INNER JOIN B
ON A.ID_PERSON = B.ID_PERSON;;

SELECT * FROM  MV_KDA;

--18
CREATE DATABASE LINK pdb_kda
CONNECT TO system
IDENTIFIED BY Qwerty123
USING 'pdb_kda';

SELECT * FROM DBA_TABLES@pdb_kia;

DROP DATABASE LINK pdb_kia;




