--1
SELECT * FROM DBA_TABLESPACES; --яохянй бяеу рюакхвмшу опнярпюмярб
--2
SELECT * FROM DBA_DATA_FILES; --яохянй бяеу тюикнб рюакхвмшу опнярпюмярб
SELECT * FROM V$LOGFILE;
--3
SELECT GROUP#, MEMBERS, STATUS FROM V$LOG; --оепевемэ бяеу цпсоо фспмюкнб онбрнпю
--4
SELECT * FROM V$LOG; --оепевемэ тюикнб бяеу фспмюкнб онбрнпю
--5
ALTER SESSION SET CONTAINER = CDB$ROOT;

ALTER SYSTEM SWITCH LOGFILE;
SELECT GROUP#, SEQUENCE#, BYTES, MEMBERS, STATUS, FIRST_CHANGE# FROM V$LOG;

ALTER SESSION SET CONTAINER = PDB_KDA;
--6
ALTER SESSION SET CONTAINER = CDB$ROOT;

ALTER DATABASE ADD LOGFILE GROUP 4 'C:\app\ora_install_KDA\oradata\orcl\KDAREDO05.LOG'
SIZE 50M BLOCKSIZE 512;
SELECT GROUP#, SEQUENCE#, BYTES, MEMBERS, STATUS, FIRST_CHANGE# FROM V$LOG;

ALTER DATABASE ADD LOGFILE MEMBER 'C:\app\ora_install_KDA\oradata\orcl\KDAREDO020.LOG' TO GROUP 4;
ALTER DATABASE ADD LOGFILE MEMBER 'C:\app\ora_install_KDA\oradata\orcl\KDAREDO021.LOG' TO GROUP 4;
ALTER DATABASE ADD LOGFILE MEMBER 'C:\app\ora_install_KDA\oradata\orcl\KDAREDO022.LOG' TO GROUP 4;

SELECT GROUP#, SEQUENCE#, BYTES, MEMBERS, STATUS, FIRST_CHANGE# FROM V$LOG;
ALTER SYSTEM SWITCH LOGFILE;
SELECT GROUP#, SEQUENCE#, BYTES, MEMBERS, STATUS, FIRST_CHANGE# FROM V$LOG;
--7
ALTER DATABASE DROP LOGFILE MEMBER 'C:\app\ora_install_KDA\oradata\orcl\KDAREDO020.LOG';
ALTER DATABASE DROP LOGFILE MEMBER 'C:\app\ora_install_KDA\oradata\orcl\KDAREDO021.LOG';
ALTER DATABASE DROP LOGFILE MEMBER 'C:\app\ora_install_KDA\oradata\orcl\KDAREDO022.LOG';

SELECT GROUP#, SEQUENCE#, BYTES, MEMBERS, STATUS, FIRST_CHANGE# FROM V$LOG;
ALTER DATABASE DROP LOGFILE GROUP 4;
SELECT GROUP#, SEQUENCE#, BYTES, MEMBERS, STATUS, FIRST_CHANGE# FROM V$LOG;

ALTER SYSTEM SWITCH LOGFILE;
SELECT GROUP#, SEQUENCE#, BYTES, MEMBERS, STATUS, FIRST_CHANGE# FROM V$LOG;
ALTER SYSTEM CHECKPOINT;
--8
SELECT NAME, LOG_MODE FROM V$DATABASE;

SELECT INSTANCE_NAME, ARCHIVER, ACTIVE_STATE FROM V$INSTANCE;

SELECT * FROM V$LOG;

ALTER SESSION SET CONTAINER = CDB$ROOT;

ALTER SYSTEM SWITCH LOGFILE;
SELECT * FROM V$ARCHIVED_LOG;

ALTER SYSTEM SWITCH LOGFILE;
SELECT GROUP#, SEQUENCE#, BYTES, MEMBERS, STATUS, FIRST_CHANGE# FROM V$LOG;

SELECT NAME, FIRST_CHANGE#, NEXT_CHANGE# FROM V$ARCHIVED_LOG;

ARCHIVE LOG LIST;

SHOW PARAMETER DB_RECOVERY;

select * from v$controlfile;